name: nexttick
description: "A modern Flutter habit tracking app with GitHub integration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Database & Storage
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # UI & Design
  fl_chart: ^0.69.0
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # Network & API
  http: ^1.2.1
  dio: ^5.4.3+1
  connectivity_plus: ^5.0.2

  # Utilities
  intl: ^0.20.2
  uuid: ^4.4.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.5
  path: ^1.9.0

  # JSON & Serialization
  json_annotation: ^4.9.0

  # Date & Time
  timezone: ^0.10.0

  # Notifications
  flutter_local_notifications: ^19.3.0

  # GitHub Integration
  github: ^9.0.0

  # ✅ Syncfusion Calendar Support
  syncfusion_flutter_calendar: ^30.1.38
  syncfusion_flutter_core: ^30.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Quality & Linting (Enhanced for NextTick standards)
  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0
  
  # Code Generation (Keep existing)
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  
  # Testing Framework (Enhanced)
  mockito: ^5.4.4
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter
  
  # Development & Quality Tools
  coverage: ^1.7.1
  

flutter:
  uses-material-design: true